fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black 01_new_project/log_analyzer
        language: system
        types: [file, python]

      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [file, python]

      # - id: mypy
      #   name: mypy
      #   entry: poetry run mypy 01_new_project/log_analyzer --exclude=__init__
      #   language: system
      #   types: [file, python]
